# Generated by Django 3.2.5 on 2021-09-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_present',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_request',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
